name: creativedata_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  agora_rtc_engine: ^1.0.8
  animated_text_kit: ^2.5.4
  cached_network_image: ^2.5.0
  chewie: ^1.0.0
  flutter_sound_lite: ^7.8.4
  cloud_firestore: ^0.14.0
  cupertino_icons: ^1.0.2
  emoji_picker: ^0.1.0
  firebase_auth: ^0.18.1+2
  webview_flutter: ^2.0.12
  open_file: ^3.2.1
  flutter_inappwebview: ^4.0.0
  flutter_downloader: ^1.7.0
  flutter_pdfview: ^1.0.4
  file_picker: ^2.1.7
  firebase_core: ^0.5.0+1
  firebase_storage: ^5.2.0
  firebase_messaging: ^7.0.3
  assets_audio_player: ^2.0.13+1
  flutter_local_notifications: ^1.4.4+2
  fluttertoast: ^8.0.2
  flutter_geofire: ^1.0.3
  internet_connection_checker: ^0.0.1+3
  overlay_support: ^1.2.1
  flutter_polyline_points: ^0.2.4
  avatar_glow: ^2.0.1
  random_string: ^2.3.1
  animations: ^2.0.1
  focused_menu: ^1.0.5
  font_awesome_flutter: ^8.10.0
  geolocator: ^6.1.1
  google_maps_flutter: ^1.0.3
  http: ^0.12.2
  image: ^2.1.18
  keyboard_visibility: ^0.5.6
  image_picker: ^0.6.7
  intl: ^0.16.1
  path_provider: ^1.6.8
  path: ^1.8.0
  grouped_list: ^4.1.0
  permission_handler: ^3.0.0
  photo_view: ^0.11.1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.4
  smooth_star_rating: ^1.1.1
  syncfusion_flutter_calendar: ^19.1.64
  url_launcher: ^5.7.10
  video_compress: ^3.0.0
  video_player: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/car_android.png
     - images/car_ios.png
     - images/desticon.png
     - images/logo.png
     - images/logo1.png
     - images/pickicon.png
     - images/posimarker.png
     - images/redmarker.png
     - images/taxi.png
     - images/user_icon.png
     - images/covid19_1.png
     - images/covid19_2.png
     - images/desticon1.png
     - images/ambulance.png
     - images/ambulance2.png
     - images/ambulance_icon.png
     - images/facebook.png
     - images/instagram.png
     - images/wallpaper.jpg
     - images/twitter.png
     - images/website.png
     - images/case.png
     - images/ihk.png
     - images/mulago.png
     - images/kibuli.png
     - images/doctor.png
     - images/drugs.png
     - images/drugs2.png
     - images/hospital.png
     - images/lab.png
     - images/eye.png
     - images/lungs.png
     - images/brain.png
     - images/tooth.png
     - images/stethoscope.png
     - images/heart.png
     - sounds/alert.mp3
     - sounds/dail_tone.mp3
     - sounds/user_unavailable.mp3
     - sounds/doc_unavailable.mp3
     - sounds/msg_sent.mp3
     - sounds/liked_post.mp3
     - sounds/recording.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brand-Regular
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
